### ISSUE TITLE
Edge data

### ISSUE THREAD

**Issue by jing-IG** [jason718/game-feature-learning#4]
Thanks for sharing the code. 

I couldn't find any info regarding where to get the ground-truth edges. In SceneNet, there is a script for generating normals from depth data. But how are edge images generated?

**Comment by jason718** [comment]
Our paper Sec.3.1 describes how we generate the edges.

"We therefore instead opt to extract edges from the instance-level segmentation masks, which alleviates the issues with noisy instance labels. For this, we simply run the canny edge detector on the segmentation masks. Since the edges are extracted from instance-level segmentations, they correspond to semantic edges (i.e., contours of objects) as opposed to low-level edges....."

we were using SUNCG and it provides instance segmentation.
